elastic-query-service:
  backPressure-delay-ms: 500 # adds delay for each record and returns it in chunks to client

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

elastic-query-config:
  text-field: text

kafka-config:
  topic-name: twitter-analytics-topic-2
  topic-names-to-create:
    - twitter-analytics-topic-2
  num-of-partitions: 3
  replication-factor: 3
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092 # hostname and port numbers from docker compose file
  schema-registry-url: http://localhost:8081 # also defined in docker compose file kafka_cluster.yml
  #schema-registry-url-key: schema.registry.url
  sleep-time-ms: 1000
  max-interval-ms: 10000
  retry-multiplier: 2.0
  admin-retry-max: 1

server:
  port: 8182

spring:
  webflux:
    base-path: /reactive-elastic-query-service
  codec:
    max-in-memory-size: 25MB # spring webflux max memory size; default 256kB
  data:
    elasticsearch:
      client:
        reactive:
          max-in-memory-size: 25MB # elasticsearch max memory size; default 256kB
