server:
  port: 8183
  servlet:
    context-path: /elastic-query-service # required to set up context path for web application

elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
