server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client: # this prefix requires class with prefix "elastic-query-web-client"
  webclient: # THIS PREFIX REQUIRES INNER CLASS WITH THIS NAME (webclient) and we do not need to use @ConfigurationProperties(prefix = "webclient")
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10 MB, max memory client can use
    content-type: 'application/vnd.api.v1+json' # default Content-Type and Accept type client will use
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://elastic-query-service/elastic-query-service/documents' # base URL we want to connect to with this client

spring:
  thymeleaf:
    cache: false # setting Thymeleaf cache to false allows Thymeleaf web page to be reloaded when there are changes during development

user-config: # needed for security configuration
  username: test
  password: '{cipher}baeb90d57edb9a050b97b98a7d8cabe80ee884e6fff16c22956172459a43e54d'
  roles: USER
